config/routes.rb
CEAD::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions' }

  # resources :zipcodes
  get '/resources', to: 'users#resources'

  post '/incoming_mails' => 'incoming_mails#create'

  root 'home#index'
  get '/neighborhoods', to: 'neighborhoods#index'
  get '/print/:zip', to: 'users#print', :as => :user_print
  # get '/neighborhoods', to: 'neighborhoods#index'
  get '/cooling', to: 'cooling_centers#show', :defaults => { :format => 'json' }
  get '/publish', to: 'emails#published_images', :defaults => { :format => 'json' }
  get '/users', to: 'users#show', :defaults => { :format => 'json' }
  # get '/form', to: 'users#form'
  match '/form', to: 'users#form', via: [:get, :post]
  match '/form-residential', to: 'users#residential', via: [:get, :post]
  match '/form-business', to: 'users#business', via: [:get, :post]
  post '/process' => 'users#process'
  get '/retro', to: 'buildings#index', :defaults => { :format => 'json' }
  get '/resource', to: 'resources#show', :defaults => { :format => 'json' }
  get '/zipcode_results', to: 'zipcodes#search', :defaults => { :format => 'json' }
  get '/cooling_search', to: 'cooling_centers#index', :defaults => { :format => 'json' }
  get '/neighbors', to: 'neighborhoods#index', :defaults => { :format => 'json' }
  get '/tweets', to: 'tweets#index', :defaults => { :format => 'json' }
  get '/incidents', to: 'incidents#index', :defaults => { :format => 'json' }
  get '/search', to: 'search#search' #, :defaults => { :format => 'json' }

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :validatable
  # has_and_belongs_to_many :neighborhoods
  has_and_belongs_to_many :admin_users
  has_and_belongs_to_many :leaders
  has_one :zipcode
  geocoded_by :full_street_address
  after_validation :geocode, :if => :address_changed?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :omniauthable, :omniauth_providers => [:facebook]

  def full_street_address
    [address, address2, city, 'CA', zip].compact.join(', ')
  end

  # def facebook
  #   # You need to implement the method below in your model (e.g. app/models/user.rb)
  #   @user = User.from_omniauth(request.env["omniauth.auth"])

  #   if @user.persisted?
  #     sign_in_and_redirect @user
   #    :event => :authentication #this will throw if @user is not activated
  #     set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
  #   else
  #     session["devise.facebook_data"] = request.env["omniauth.auth"]
  #     redirect_to new_user_registration_url
  #   end
  # end


  def self.as_csv
    headers = ['email','phone','name','address','address2','zip','nert','cert','cpr','safe','firstaid','dumptruck','backhoe','forklift','fuel','generator','saw','jackhammer','emergency','drill','hammer','shovel','emergency_contact','engineer','contractor','underground','overnight','oxygen','wheelchair','defibrillation','other','latitude','longitude','firstresponder','inspector','commercial','electrician','carpenter','operator','plumber','kitchen','bulldozer','excavator','frontloader','reclaimer','trencher','tractor','goggles','axe', 'rescue', 'flashlight'] 
    CSV.generate do |csv|
      csv << headers
      all.each do |item|
        csv << item.attributes.values_at(*headers)
      end
    end
  end

  def self.form_csv
    CSV.open "form.csv", "a+" do |csv|
      csv << [status,first_name,last_name,phone_number,email,address,city,state,zip]
    end
    # headers = ['name','last_name','address','zip','city','state','phone_number','email']
    # CSV.generate do |csv|
    #   csv << headers
    #   all.each do |item|
    #     csv << item.attributes.values_at(*headers)
    #   end
    # end
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def update_with_password(params={})
    current_password = params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end 

    result = params[:password].blank? && if params[:password].blank? || valid_password?(current_password)
      update_attributes(params)
    else
      self.attributes = params
      self.valid?
      self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
      false
    end 

    clean_up_passwords
    result
  end
  #  searchable do
  #   string :name
  #   # text :address
  #   # integer :zip
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # layout "form", :only => [:form]
  layout "residential", :only => [:residential]

  def print
    @user = User.where(zip: params[:zip])
    p @user
    respond_to do |format|
      format.html { render :layout => false, :only => [:print] }
      format.csv {render text: @user.as_csv}
      format.xls
    end
  end

  # def index
  #   @user = User.order(:name)
  #   respond_to do |format|
  #     format.html
  #     format.csv {render text: @user.as_csv}
  #   end
  # end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      session[:modal] = true
      redirect_to root_path
    else
      render 'new'
    end
  end


  def show
    @users = User.all
    respond_to do |format|
      format.html
      # format.csv {render text: @users.as_csv}
      # format.xls {render text: @users.as_csv(col_sep: '\t')}
      format.json { render json: @users }
    end
  end


  def update
    @user = current_user
    if @user.update_attributes(user_params)
      render :partial => 'users/personal'
    else
      render 'home/edit'
    end
  end

  def resources
    @users = User.all
  end

  def form
    respond_to do |format|
      format.html { render :layout => 'form', :only => [:form] }
      # format.csv {render text: @user.as_csv}
      # format.xls
    end
  end
  def residential
  end
  def business
    respond_to do |format|
      format.html { render :layout => 'business', :only => [:business] }
      # format.csv {render text: @user.as_csv}
      # format.xls
    end
  end
  # def process
  #   CSV.open "form.csv", "a+" do |csv|
  #     csv << [params[:status],params[:first_name],params[:last_name],params[:phone_number],params[:email],params[:address],params[:city],params[:state],params[:zip]]
  #   end
  #   # logger.debug params.inspect
  #   # render :user => 'form'
  # end
  
end

app/views/users/_personal.html.haml
- if current_user
  %h3 My Account
  .height
    = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
      .row
        .personal.col-md-3#contact-info 
          Personal Information
          .account-box
            = f.label :name
            = f.text_field :name, value: current_user.name, id: 'name_field', :required => true
            %br
            = f.label(:last_name, 'Last Name')
            = f.text_field :last_name, value: current_user.name, id: 'last_name_field', :required => true
            %br
            = f.label :email
            = f.email_field :email, value: current_user.email, id: 'email_field'
            %br
            = f.label :phone
            = f.text_field :phone, value: current_user.phone, id: 'phone_field'
            %br
            = f.label :address
            = f.text_field :address, value: current_user.address, id: 'address_field', :required => true
            %br
            = f.label :address2
            = f.text_field :address2, value: current_user.address2
            %br
            = f.label :city
            = f.text_field :city, value: current_user.city, id: 'city_field'
            %br
            = f.label :state
            = select_tag(options_for_select([['NY'], ['CA']]))
            %br
            = f.label :zip
            = f.text_field :zip, value: current_user.zip, id: 'zip_field', :required => true
            %br
            If Volunteer:
            %br
            = f.radio_button :volunteer, true, {:checked => current_user.volunteer? == true}
            = f.label(:volunteer, 'Available')
            %br
            = f.radio_button :volunteer, false, {:checked => current_user.volunteer? == false}
            = f.label(:volunteer, 'Not Available')
        .personal.col-md-3#person-info 
          Are you a:
          .account-box
            = f.check_box :business, {:checked=>current_user.business}
            = f.label :business
            %br
            = f.check_box :faith, {:checked=>current_user.faith}
            = f.label(:faith, 'Faith Based Organization')
            %br
            = f.check_box :gov, {:checked=>current_user.gov}
            = f.label(:gov, 'Government Entity')
            %br
            = f.check_box :individual, {:checked=>current_user.individual}
            = f.label(:individual, 'Individual')
            %br
            = f.check_box :ngo, {:checked=>current_user.ngo}
            = f.label(:ngo, 'NGO')
            %br
            = f.label(:duns_number,'DUNS Number')
            = f.text_field :duns_number, value: current_user.duns_number, id: 'duns_field', :class => 'numbers'
            %br
            %br
          Are you:
          .account-box
            = f.check_box :open, {:checked=>current_user.open}
            = f.label :open
            %br
            = f.check_box :closed, {:checked=>current_user.closed}
            = f.label :closed
        .personal.col-md-3#certifications 
          Certifications
          .account-box
            = f.check_box :cert, {:checked=>current_user.cert}
            = f.label(:cert, 'CERT')
            %br
            = f.check_box :nert, {:checked=>current_user.nert}
            = f.label(:nert, 'NERT')
            %br
            = f.check_box :cpr, {:checked=>current_user.cpr}
            = f.label(:cpr, 'CPR')
            %br
            = f.check_box :safe, {:checked=>current_user.safe}
            = f.label(:safe, 'SAFE')
            %br
            = f.check_box :firstaid, {:checked=>current_user.firstaid}
            = f.label(:firstaid, 'First Aid')
            %br
            = f.check_box :firstresponder, {:checked=>current_user.firstresponder}
            = f.label(:firstresponder, 'First Responder')
            %br
            = f.check_box :rescue, {:checked=>current_user.rescue}
            = f.label(:rescue, 'Light Search & Rescue')
            %br
            = f.label(:certification_number, 'Certification Number')
            = f.text_field :certification_number, value: current_user.certification_number, id: 'certification_field', :class => 'numbers'
            = f.text_field :certification2_number, value: current_user.certification2_number, id: 'certification2_field', :class => 'numbers'
        .personal.col-md-3#user-buildings 
          Certificated Skills - Trade
          .account-box
            = f.check_box :inspector,{:checked=>current_user.inspector}
            = f.label(:inspector, 'Building Inspector')
            %br
            = f.check_box :carpenter,{:checked=>current_user.carpenter}
            = f.label :carpenter
            %br
            = f.check_box :commercial,{:checked=>current_user.commercial}
            = f.label(:commercial, 'Commercial License')
            %br
            = f.check_box :electrician,{:checked=>current_user.electrician}
            = f.label 'Electrician'
            %br
            = f.check_box :contractor,{:checked=>current_user.contractor}
            = f.label(:contractor, 'General Contractor')
            %br
            = f.check_box :operator,{:checked=>current_user.operator}
            = f.label(:operator, 'Heavy Equipment Operator')
            %br
            = f.check_box :plumber,{:checked=>current_user.plumber}
            = f.label :plumber
            %br
            = f.check_box :engineer,{:checked=>current_user.engineer}
            = f.label(:engineer,'Structural Engineer')
            %br
            = f.label(:license_number, 'License Number')
            = f.text_field :license_number, value: current_user.license_number, id: 'license_field', :class => 'numbers'
            = f.text_field :license2_number, value: current_user.license2_number, id: 'license_field2', :class => 'numbers'
            %br
            = f.label :other
            = f.text_field :other, value: current_user.other, id: 'other_field', :class => 'numbers' 
        
      %br
      .personal.col-md-3#assistance 
        Assistance
        .account-box
          = f.check_box :meals, {:checked=>current_user.meals}
          = f.label(:meals, 'Meals')
          %br
          = f.check_box :gather, {:checked=>current_user.gather}
          = f.label(:gather, 'Place to Gather')
          %br
          = f.check_box :clothing, {:checked=>current_user.clothing}
          = f.label(:clothing, 'Clothing/Blankets')
          %br
          = f.check_box :spiritual, {:checked=>current_user.spiritual}
          = f.label(:spiritual, 'Spiritual/Emotional Support')
          %br
          = f.label :other
          = f.text_field :other, value: current_user.other, id: 'other_field', :class => 'numbers' 
      .personal#user-resources 
        Resources
        .account-box.row
          .col-md-3
            Facilities
            %br
            = f.check_box :generator, {:checked=>current_user.generator}
            = f.select :generator_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.generator_q)
            = f.label(:generator,'Back-up Generator Facility')
            %br
            = f.check_box :kitchen, {:checked=>current_user.kitchen}
            = f.select :kitchen_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.kitchen_q)
            = f.label(:kitchen,'Commercial Kitchen')
            %br
            = f.check_box :overnight, {:checked=>current_user.overnight}
            = f.select :overnight_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.overnight_q)
            = f.label(:overnight,'Overnight Shelter')
            %br
            = f.check_box :underground, {:checked=>current_user.underground}
            = f.select :underground_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.underground_q)
            = f.label(:underground,'Underground Shelter')
            %br
            Medical
            %br
            = f.check_box :defibrillation, {:checked=>current_user.defibrillation}
            = f.select :defibrillation_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.defibrillation_q)
            = f.label 'Defibrillator'
            %br
            = f.check_box :emergency, {:checked=>current_user.emergency}
            = f.select :emergency_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.emergency_q)
            = f.label(:emergency,'Emergency Kit') 
            %br
            = f.check_box :oxygen, {:checked=>current_user.oxygen}
            = f.select :oxygen_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.oxygen_q)
            = f.label :oxygen
            %br
            = f.check_box :wheelchair, {:checked=>current_user.wheelchair}
            = f.select :wheelchair_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.wheelchair_q)
            = f.label 'Wheelchair'
            %br
          .col-md-3
            Heavy Equipment
            %br
            = f.check_box :backhoe, {:checked=>current_user.backhoe}
            = f.select :backhoe_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.backhoe_q)
            = f.label(:backhoe,'Backhoe')
            %br
            = f.check_box :bulldozer, {:checked=>current_user.bulldozer}
            = f.select :bulldozer_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.bulldozer_q)
            = f.label :bulldozer
            %br
            = f.check_box :dumptruck, {:checked=>current_user.dumptruck}
            = f.select :dumptruck_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.dumptruck_q)
            = f.label(:dumptruck,'Dump Truck')
            %br
            = f.check_box :excavator, {:checked=>current_user.excavator}
            = f.select :excavator_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.excavator_q)
            = f.label :excavator
            %br
            = f.check_box :forklift, {:checked=>current_user.forklift}
            = f.select :forklift_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.forklift_q)
            = f.label(:forklift, 'Fork Lift')
            %br
            = f.check_box :frontloader, {:checked=>current_user.frontloader}
            = f.select :frontloader_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.frontloader_q)
            = f.label(:frontloader, 'Front Loader')
            %br
            = f.check_box :jackhammer, {:checked=>current_user.jackhammer}
            = f.select :jackhammer_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.jackhammer_q)
            = f.label(:jackhammer, 'Jack Hammer')
            %br
            = f.check_box :reclaimer, {:checked=>current_user.reclaimer}
            = f.select :reclaimer_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.reclaimer_q)
            = f.label :reclaimer
            %br
            = f.check_box :tractor, {:checked=>current_user.tractor}
            = f.select :tractor_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.tractor_q)
            = f.label :tractor
            %br
            = f.check_box :trencher, {:checked=>current_user.trencher}
            = f.select :trencher_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.trencher_q)
            = f.label :trencher
            %br
          .col-md-2
            Light Equipment
            %br
            = f.check_box :axe, {:checked=>current_user.axe}
            = f.select :axe_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.axe_q)
            = f.label :axe
            %br
            = f.check_box :drill, {:checked=>current_user.drill}
            = f.select :drill_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.drill_q)
            = f.label :drill
            %br
            = f.check_box :flashlight, {:checked=>current_user.flashlight}
            = f.select :flashlight_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.flashlight_q)
            = f.label :flashlight
            %br
            = f.check_box :fuel, {:checked=>current_user.fuel}
            = f.select :fuel_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.fuel_q)
            = f.label :fuel
            %br
            = f.check_box :goggles, {:checked=>current_user.goggles}
            = f.select :goggles_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.goggles_q)
            = f.label :goggles
            %br
            = f.check_box :hammer, {:checked=>current_user.hammer}
            = f.select :hammer_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.hammer_q)
            = f.label :hammer
            %br
            = f.check_box :shovel, {:checked=>current_user.shovel}
            = f.select :shovel_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.shovel_q)
            = f.label :shovel
            %br
            = f.check_box :sandbag, {:checked=>current_user.sandbag}
            = f.select :sandbag_q, options_for_select((0..30).map {|i| [i,i] } << ["No limit",nil], current_user.sandbag_q)
            = f.label :sandbag
            %br
        #update
          = f.submit 'UPDATE'

app/views/users/form.html.erb
<div class='top_bar'>
  <div id='logo_container'>
    <img id='logo_img' src='./images/appa_a_white.png'>
    <span id='appa_text'>APPALLICIOUS</span>
  </div>
</div>
<h2 class='center'>DAAD Data Form</h2>

<div class='center'>
  <%= form_tag '/form' do %>

  
    <div class='upper_middle'>  
      <h4 class='underline'>Status</h4>
      <p>As which entity are you filling out this form?</p>
      <div> 
        <div class='radio_div'>
          <input type="radio" name="status" value="individual"><span class='radio_text'>An  Individual</span>
        </div>
        <div class='radio_div'>
          <input type="radio" name="status" value="ngo"><span class='radio_text'>A Non- governmental Organization</span>
        </div>
      </div>
      <div> 
        <div class='radio_div'>
          <input type="radio" name="status" value="business"><span class='radio_text'>A Business</span>
        </div>
        <div class='radio_div'>
          <input type="radio" name="status" value="government"><span class='radio_text'>A   Government Representative</span>
        </div>
      </div>
    </div>
    
    <div class='middle'>  
      <h4 class='underline'>Personal Information</h4>
      <div>  
        <div class='left_form'>
          <%= label_tag "First Name" %>
          <%= text_field_tag "name" %>
          <!-- <p class='form_title'>First Name:</p> -->
          <input type="text" name="name" class='input'>
        </div>
        <div class='right_form'>
          <p>Last Name:</p>
          <input type="text" name="name" class='input'>
        </div>
      </div>
      <div>
        <div class='left_form'>
          <p>Phone Number:</p>
          <input type="text" name="phone_number" class='input'>
        </div>
        <div class='right_form'>
          <p>Email:</p>
          <input type="text" name="email" class='input'>
        </div>
      </div>
    </div>
    <br>
    
    <div class='middle'>
      <h4 class='underline'>Address</h4>
      <div>  
        <div class='left_form'>
          <p>Address:</p>
          <input type="text" name="address" class='input'>
        </div>
        <div class='right_form'>
          <p>City:</p>
          <input type="text" name="city" value="San Francisco" class='input'>
        </div>
      </div>
      <div>
        <div class='left_form'>
          <p>State:</p>
          <input type="text" name="state" value="California" class='input'>
        </div>
        <div class='right_form'>
          <p>Zipcode:</p>
          <input type="text" name="zipcode" class='input'>
        </div>
      </div>
    </div>

    <br><br>
    <input type="submit" value="Submit">
    <br><br>
  <% end %>

</div>

app/views/users/print.html.haml
#user-print
  %head
    = stylesheet_link_tag    "application", media: "all" #, "data-turbolinks-track" => true
  %body
    .print-header
      %a(href='/')
        =image_tag("appa_logo3.png",width:'300px')
      Community Resources - San Francisco, CA
      %br
      %br
      = link_to "CSV", user_print_path(format: "csv"), class: 'map-buttons2'
      = link_to "Excel", user_print_path(format: "xls"), class: 'map-buttons2'
      = link_to "Print", 'javascript:window.print()', class: 'map-buttons2'
    %br
    %table.user-table
      %tr
        %th.blue2 Certifications
        %th NERT
        %th CERT
        %th CPR
        %th SAFE
        %th First Aid
        %th First Responder
        %th Light Search & Rescue
      - @user.all.each do |u|
        %tr
          %th{style: 'min-width: 140px;'}
            = u.name
            %br
            = u.address
            = u.address2
          - u.attributes.each do |attr_name, attr_value|
            - if attr_name == 'cert'
              %td
                = image_tag("#{attr_value}.png", size: "20x20")
            - if attr_name == 'nert'
              %td
                = image_tag("#{attr_value}.png", size: "20x20")
            - if attr_name == 'cpr'
              %td
                = image_tag("#{attr_value}.png", size: "20x20")
            - if attr_name == 'safe'
              %td
                = image_tag("#{attr_value}.png", size: "20x20")
            - if attr_name == 'firstaid'
              %td
                = image_tag("#{attr_value}.png", size: "20x20")
            - if attr_name == 'firstresponder'
              %td
                = image_tag("#{attr_value}.png", size: "20x20")
            - if attr_name == 'rescue'
              %td
                = image_tag("#{attr_value}.png", size: "20x20")    
      %table.user-table
        %tr
          %th.blue2 Skills
          %th Building Inspector
          %th Carpenter
          %th Commercial License
          %th General Contractor
          %th Electrician
          %th Engineer
        - @user.all.each do |u|
          %tr.space
            %th{style: 'min-width: 140px;'}
              = u.name
              %br
              = u.address
              = u.address2
            - u.attributes.each do |attr_name, attr_value|
              - if attr_name == 'inspector'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'carpenter'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'commercial'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'contractor'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'electrician'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'engineer'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
      %table.user-table
        %tr
          %th.blue2 Facilities
          %th Backup Generator
          %th Industrial Kitchen
          %th Overnight Shelter
          %th Underground Shelter
        - @user.all.each do |u|
          %tr
            %th{style: 'min-width: 140px;'}
              = u.name
              %br
              = u.address
              = u.address2
            - u.attributes.each do |attr_name, attr_value|
              - if attr_name == 'generator'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'kitchen'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'overnight'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'underground'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
      %table.user-table
        %tr
          %th.blue2 Medical
          %th Defibrillator
          %th Emergency Kit
          %th Oxygen
          %th Wheelchair
        - @user.all.each do |u|
          %tr
            %th{style: 'min-width: 140px;'}
              = u.name
              %br
              = u.address
              = u.address2
            - u.attributes.each do |attr_name, attr_value|
              - if attr_name == 'defibrillation'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'emergency'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'oxygen'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'wheelchair'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
      %table.user-table
        %tr
          %th.blue2 Equipment - Heavy
          %th Backhoes
          %th Bulldozer
          %th Dumptruck
          %th Excavator
          %th Fork Lift
          %th Front Loader
          %th Jackhammer
          %th Reclaimer
          %th Tractor
        - @user.all.each do |u|
          %tr
            %th{style: 'min-width: 140px;'}
              = u.name
              %br
              = u.address
              = u.address2
            - u.attributes.each do |attr_name, attr_value|
              - if attr_name == 'backhoe'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'bulldozer'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'dumptruck'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'excavator'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'forklift'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'frontloader'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'jackhammer'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'reclaimer'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'tractor'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
      %table.user-table
        %tr
          %th.blue2 Equipment - Light
          %th Axe
          %th Drill
          %th Fuel
          %th Goggles
          %th Hammer
          %th Shovel
          %th Flashlight
        - @user.all.each do |u|
          %tr
            %th{style: 'min-width: 140px;'}
              = u.name
              %br
              = u.address
              = u.address2
            - u.attributes.each do |attr_name, attr_value|
              - p attr_name
              - p attr_value
              - if attr_name == 'axe'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'drill'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'fuel'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'goggles'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'hammer'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'shovel'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")
              - if attr_name == 'flashlight'
                %td
                  = image_tag("#{attr_value}.png", size: "20x20")